export const LOGIN_REQUEST = 'LOGING_REQUEST'
export const LOGIN_SUCCESS = 'LOGING_SUCCESS'
export const LOGIN_FAIL = 'LOGING_FAIL'

export const REGISTER_USER_REQUEST='REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'


export const CLEAR_ERRORS='CLEAR_ERRORS'
